// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'my_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN9fquKUltTNWb0VJo74g1185a9CaY7uE',
    appId: '1:455751492446:web:b680b12229bea51fb2a5cf',
    messagingSenderId: '455751492446',
    projectId: 'codelab-training-eecd6',
    authDomain: 'codelab-training-eecd6.firebaseapp.com',
    storageBucket: 'codelab-training-eecd6.appspot.com',
    measurementId: 'G-5N1PXS009P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRcEG6LL34jsbsmkCxH-4Xg1qVs5hnzRU',
    appId: '1:455751492446:android:aaef36d190f646e8b2a5cf',
    messagingSenderId: '455751492446',
    projectId: 'codelab-training-eecd6',
    storageBucket: 'codelab-training-eecd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-WcuYCcatdi1ieCneSr3Qmn7NIBD9JHk',
    appId: '1:455751492446:ios:55e9333c92f4f8eeb2a5cf',
    messagingSenderId: '455751492446',
    projectId: 'codelab-training-eecd6',
    storageBucket: 'codelab-training-eecd6.appspot.com',
    iosBundleId: 'com.example.codelabTraining',
  );
}
